import { Frame } from './frame';

export const FRAMES: Frame[] = [
  { path: '../assets/img/1.png', exercise: 1 },
  { path: '../assets/img/2.png', exercise: 1 },
  { path: '../assets/img/3.png', exercise: 1 },
  { path: '../assets/img/4.png', exercise: 1 },
  { path: '../assets/img/5.png', exercise: 1 },
  { path: '../assets/img/6.png', exercise: 1 },
  { path: '../assets/img/7.png', exercise: 1 },
  { path: '../assets/img/8.png', exercise: 1 },
  // { path: 'https://downloader.disk.yandex.ru/preview/eb067b608e62e0a3ba63ef183b851386e202f02e8441e0c2a2fe79e9abb2429b/5bdd9a93/KIHv5FzXGcSf1FYqOYVak8h-aMe-PGjNT4ITjC6F2q1Yv4YJLx_fg9fkSS-J303_LTqWUSs63ukBuoGNcDrnXg%3D%3D?uid=0&filename=9.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&size=2048x2048', exercise: 1 },
  { path: '../assets/img/1 - копия.png', exercise: 2 },
  { path: '../assets/img/2 - копия.png', exercise: 2 },
  { path: '../assets/img/3 - копия.png', exercise: 2 },
  { path: '../assets/img/4.png', exercise: 2 },
  { path: '../assets/img/5.png', exercise: 2 },
  { path: '../assets/img/6.png', exercise: 2 },
  { path: '../assets/img/7.png', exercise: 2 },
  { path: '../assets/img/8.png', exercise: 2 },
  { path: '../assets/img/9.png', exercise: 2 },
  { path: '../assets/img/1.png', exercise: 3 },
  { path: '../assets/img/2.png', exercise: 3 },
  { path: '../assets/img/3.png', exercise: 3 },
  { path: '../assets/img/4.png', exercise: 3 },
  { path: '../assets/img/5.png', exercise: 3 },
  { path: '../assets/img/6.png', exercise: 3 },
  { path: '../assets/img/7.png', exercise: 3 },
  { path: '../assets/img/8.png', exercise: 3 },
  { path: '../assets/img/9.png', exercise: 3 },
  { path: '../assets/img/1 - копия.png', exercise: 4 },
  { path: '../assets/img/2 - копия.png', exercise: 4 },
  { path: '../assets/img/3 - копия.png', exercise: 4 },
  { path: '../assets/img/4.png', exercise: 4 },
  { path: '../assets/img/5.png', exercise: 4 },
  { path: '../assets/img/6.png', exercise: 4 },
  { path: '../assets/img/7.png', exercise: 4 },
  { path: '../assets/img/8.png', exercise: 4 },
  { path: '../assets/img/9.png', exercise: 4 },
  { path: '../assets/img/1.png', exercise: 5 },
  { path: '../assets/img/2.png', exercise: 5 },
  { path: '../assets/img/3.png', exercise: 5 },
  { path: '../assets/img/4.png', exercise: 5 },
  { path: '../assets/img/5.png', exercise: 5 },
  { path: '../assets/img/6.png', exercise: 5 },
  { path: '../assets/img/7.png', exercise: 5 },
  { path: '../assets/img/8.png', exercise: 5 },
  { path: '../assets/img/9.png', exercise: 5 },
  { path: '../assets/img/1 - копия.png', exercise: 6 },
  { path: '../assets/img/2 - копия.png', exercise: 6 },
  { path: '../assets/img/3 - копия.png', exercise: 6 },
  { path: '../assets/img/4.png', exercise: 6 },
  { path: '../assets/img/5.png', exercise: 6 },
  { path: '../assets/img/6.png', exercise: 6 },
  { path: '../assets/img/7.png', exercise: 6 },
  { path: '../assets/img/8.png', exercise: 6 },
  { path: '../assets/img/9.png', exercise: 6 },
]
